[db]
main ansible_host=51.250.76.194 fqdn=main.ru-central1.internal
replica ansible_host=89.169.150.216 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=84.201.159.52 fqdn=storage.ru-central1.internal

[web]
web-1 ansible_host=89.169.157.184 fqdn=web-1.ru-central1.internal
web-2 ansible_host=89.169.142.154 fqdn=web-2.ru-central1.internal

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
